

export const alimentos = [
    {
        nombre: "",
        unidad: "",
        cantidad: 1,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 0,
        calorias: 0,
    },
    {
        nombre: "Aceite de Oliva",
        unidad: "cuchara",
        cantidad: 1,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 10,
        calorias: 90,
    },
    {
        nombre: "Arroz blanco ",
        unidad: "gr",
        cantidad: 100,
        proteinas: 7.6,
        carbohidratos: 78,
        grasas: 0,
        calorias: 342,
    },
    {
        nombre: "Arroz integral",
        unidad: "gr",
        cantidad: 100,
        proteinas: 2.56,
        carbohidratos: 22.78,
        grasas: 0.89,
        calorias: 109,
    },
    {
        nombre: "Arroz Parboil",
        unidad: "gr",
        cantidad: 100,
        proteinas: 6.8,
        carbohidratos: 72,
        grasas: 0,
        calorias: 315,
    },
    {
        nombre: "Atun al Agua ",
        unidad: "gr",
        cantidad: 100,
        proteinas: 25.51,
        carbohidratos: 0,
        grasas: 0.82,
        calorias: 109,
    },
    {
        nombre: "Avena",
        unidad: "gr",
        cantidad: 100,
        proteinas: 17,
        carbohidratos: 66.27,
        grasas: 6.9,
        calorias: 395,
    },
    {
        nombre: "Banana",
        unidad: "uni",
        cantidad: 1,
        proteinas: 1.09,
        carbohidratos: 22.8,
        grasas: 0.3,
        calorias: 98,
    },
    {
        nombre: "Batata",
        unidad: "gr",
        cantidad: 100,
        proteinas: 1.61,
        carbohidratos: 24.19,
        grasas: 0.6,
        calorias: 109,
    },
    {
        nombre: "Cereal Maiz",
        unidad: "gr",
        cantidad: 30,
        proteinas: 2.1,
        carbohidratos: 26,
        grasas: 0,
        calorias: 112,
    },
    {
        nombre: "Claras de Huevo (40gr)",
        unidad: "uni",
        cantidad: 1,
        proteinas: 4.5,
        carbohidratos: 0.24,
        grasas: 0.06,
        calorias: 20,
    },
    {
        nombre: "Crema Leche",
        unidad: "cuchara",
        cantidad: 1,
        proteinas: 0.2,
        carbohidratos: 0,
        grasas: 6,
        calorias: 55,
    },
    {
        nombre: "Dulce de Leche (20gr)",
        unidad: "cuchara ",
        cantidad: 1,
        proteinas: 1.3,
        carbohidratos: 12,
        grasas: 1.3,
        calorias: 65,
    },
    {
        nombre: "Fajita Bimbo (27.5gr)",
        unidad: "uni",
        cantidad: 1,
        proteinas: 2.5,
        carbohidratos: 14,
        grasas: 1.85,
        calorias: 83,
    },
    {
        nombre: "Galleta de Arroz (10gr)",
        unidad: "uni",
        cantidad: 1,
        proteinas: 0.6,
        carbohidratos: 8.5,
        grasas: 0,
        calorias: 36,
    },
    {
        nombre: "Ganador de Peso",
        unidad: "scoop",
        cantidad: 2,
        proteinas: 23,
        carbohidratos: 60,
        grasas: 5,
        calorias: 377,
    },
    {
        nombre: "Harina de Arroz",
        unidad: "gr",
        cantidad: 100,
        proteinas: 6,
        carbohidratos: 80,
        grasas: 1,
        calorias: 353,
    },
    {
        nombre: "Harina de Trigo",
        unidad: "gr",
        cantidad: 100,
        proteinas: 11,
        carbohidratos: 72,
        grasas: 0,
        calorias: 332,
    },
    {
        nombre: "Huevo (55gr)",
        unidad: "uni ",
        cantidad: 1,
        proteinas: 6.7,
        carbohidratos: 0.38,
        grasas: 4.97,
        calorias: 73,
    },
    {
        nombre: "Jamon",
        unidad: "gr",
        cantidad: 30,
        proteinas: 5.5,
        carbohidratos: 0,
        grasas: 1,
        calorias: 31,
    },
    {
        nombre: "Leche Descremada",
        unidad: "ml",
        cantidad: 200,
        proteinas: 6,
        carbohidratos: 9.6,
        grasas: 2,
        calorias: 80,
    },
    {
        nombre: "Leche Entera",
        unidad: "ml",
        cantidad: 200,
        proteinas: 6,
        carbohidratos: 9,
        grasas: 6,
        calorias: 114,
    },
    {
        nombre: "Lecho en Polvo",
        unidad: "gr",
        cantidad: 20,
        proteinas: 6.6,
        carbohidratos: 11,
        grasas: 5,
        calorias: 115,
    },
    {
        nombre: "Lentejas",
        unidad: "gr",
        cantidad: 100,
        proteinas: 25.8,
        carbohidratos: 60.08,
        grasas: 1.06,
        calorias: 353,
    },
    {
        nombre: "Maltodextrina",
        unidad: "gr",
        cantidad: 30,
        proteinas: 0,
        carbohidratos: 30,
        grasas: 0,
        calorias: 120,
    },
    {
        nombre: "Mani Pelado",
        unidad: "gr",
        cantidad: 20,
        proteinas: 5.16,
        carbohidratos: 3.23,
        grasas: 9.85,
        calorias: 122,
    },
    {
        nombre: "Manzana",
        unidad: "uni",
        cantidad: 1,
        proteinas: 0.3,
        carbohidratos: 19,
        grasas: 0.23,
        calorias: 79,
    },
    {
        nombre: "Mermelada (20gr)",
        unidad: "cuchara ",
        cantidad: 1,
        proteinas: 0,
        carbohidratos: 14,
        grasas: 0,
        calorias: 56,
    },
    {
        nombre: "Mermelada Light (20gr)",
        unidad: "cuchara ",
        cantidad: 1,
        proteinas: 0,
        carbohidratos: 6,
        grasas: 0,
        calorias: 24,
    },
    {
        nombre: "Miel (20gr)",
        unidad: "cuchara",
        cantidad: 1,
        proteinas: 0.06,
        carbohidratos: 17.3,
        grasas: 0,
        calorias: 69,
    },
    {
        nombre: "Palta",
        unidad: "gr",
        cantidad: 100,
        proteinas: 2,
        carbohidratos: 8,
        grasas: 14,
        calorias: 166,
    },
    {
        nombre: "Pan Blanco",
        unidad: "gr",
        cantidad: 100,
        proteinas: 7.64,
        carbohidratos: 50,
        grasas: 3.3,
        calorias: 260,
    },
    {
        nombre: "Pan de Molde (25gr)",
        unidad: "rebanada",
        cantidad: 1,
        proteinas: 2.35,
        carbohidratos: 12.5,
        grasas: 0.65,
        calorias: 65,
    },
    {
        nombre: "Papa",
        unidad: "gr",
        cantidad: 100,
        proteinas: 2,
        carbohidratos: 17.47,
        grasas: 0.09,
        calorias: 79,
    },
    {
        nombre: "Pasta de mani",
        unidad: "cuchara",
        cantidad: 1,
        proteinas: 4.7,
        carbohidratos: 3.3,
        grasas: 9.5,
        calorias: 118,
    },
    {
        nombre: "Pechuga de pollo ",
        unidad: "gr",
        cantidad: 100,
        proteinas: 23,
        carbohidratos: 0,
        grasas: 1.7,
        calorias: 107,
    },
    {
        nombre: "Pochoclo",
        unidad: "gr",
        cantidad: 100,
        proteinas: 12.54,
        carbohidratos: 77.78,
        grasas: 4.4,
        calorias: 401,
    },
    {
        nombre: "Porotos",
        unidad: "gr",
        cantidad: 100,
        proteinas: 22.47,
        carbohidratos: 61.41,
        grasas: 1.45,
        calorias: 349,
    },
    {
        nombre: "Queso Cremoso",
        unidad: "gr",
        cantidad: 30,
        proteinas: 6.3,
        carbohidratos: 0,
        grasas: 7.5,
        calorias: 93,
    },
    {
        nombre: "Soja Texturizada",
        unidad: "gr",
        cantidad: 100,
        proteinas: 47,
        carbohidratos: 38,
        grasas: 1.22,
        calorias: 351,
    },
    {
        nombre: "Whey Protein",
        unidad: "scoop",
        cantidad: 1,
        proteinas: 25,
        carbohidratos: 2.6,
        grasas: 1.8,
        calorias: 127,
    },
    {
        nombre: "Yema de Huevo",
        unidad: "uni",
        cantidad: 1,
        proteinas: 2.7,
        carbohidratos: 0.6,
        grasas: 4.5,
        calorias: 54,
    },
    {
        nombre: "Yogurt ",
        unidad: "ml",
        cantidad: 200,
        proteinas: 7,
        carbohidratos: 22,
        grasas: 1.5,
        calorias: 130,
    },
    {
        nombre: "Yogurt Light",
        unidad: "ml",
        cantidad: 200,
        proteinas: 7,
        carbohidratos: 7,
        grasas: 0,
        calorias: 56,
    },
]