// Ejemplo de el arreglo de dietas
export const dietas = 
  [
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    },
    {
      desayuno: "",
      almuerzo: "",
      merienda: "",
      cena: "",
      postWork: "",
      snack: "",
      fecha: "",
      calorias: "",
      proteinas: "",
      carbohidratos: "",
      grasas: ""
    }
  ]